import { defineSchema, defineTable } from "convex/server";
import { authTables } from "@convex-dev/auth/server";
import { v } from "convex/values";

export default defineSchema({
  ...authTables,
  users: defineTable({
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.float64()),
    image: v.optional(v.string()),
    isAnonymous: v.optional(v.boolean()),
    name: v.optional(v.string()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.float64()),
    role: v.optional(v.union(v.literal("user"), v.literal("admin"))),
  })
    .index("email", ["email"])
    .index("phone", ["phone"]),
  testimonials: defineTable({
    name: v.string(),
    email: v.optional(v.string()),
    media_id: v.optional(v.id("_storage")), // Storage ID for the media type
    media_type: v.string(),
    createdAt: v.optional(v.number()), // Timestamp when testimonial was created
    title: v.optional(v.string()), // Title generated by Gemini
    testimonialText: v.optional(v.string()), // Text version of the testimonial
    summary: v.optional(v.string()), // Summary of the testimonial
    searchText: v.optional(v.string()), // Field for full-text search indexing
    approved: v.optional(v.boolean()), // Whether the testimonial is approved for display
  }).searchIndex("search_posts", {
    searchField: "searchText",
  }),
  transcription_jobs: defineTable({
    job_id: v.string(),
    testimonial_id: v.id("testimonials"),
  }),
});
