import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  testimonials: defineTable({
    name: v.string(),
    email: v.string(),
    media_id: v.optional(v.id("_storage")), // Storage ID for the media type
    media_type: v.string(),
    createdAt: v.optional(v.number()), // Timestamp when testimonial was created
    title: v.optional(v.string()), // Title generated by Gemini
    testimonialText: v.optional(v.string()), // Text version of the testimonial
    summary: v.optional(v.string()), // Summary of the testimonial
  }).searchIndex("search_name", {
    searchField: "name",
  }).searchIndex("search_text", {
    searchField: "testimonialText",
  }).searchIndex("search_summary", {
    searchField: "summary",
  }).searchIndex("search_title", {
    searchField: "title",
  }).searchIndex("search_email", {
    searchField: "email",
  }),
  transcription_jobs: defineTable({
    job_id: v.string(),
    testimonial_id: v.id("testimonials"),
  }),
});
