import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  testimonials: defineTable({
    name: v.string(),
    email: v.string(),
    media_id: v.optional(v.id("_storage")), // Storage ID for the media type
    media_type: v.string(),
    createdAt: v.optional(v.number()), // Timestamp when testimonial was created
    title: v.optional(v.string()), // Title generated by Gemini
    testimonialText: v.optional(v.string()), // Text version of the testimonial
    summary: v.optional(v.string()), // Summary of the testimonial
    searchText: v.optional(v.string()), // Field for full-text search indexing
  }).searchIndex("search_posts", {
    searchField: "searchText",
  }),
  transcription_jobs: defineTable({
    job_id: v.string(),
    testimonial_id: v.id("testimonials"),
  }),
});
