/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestimonialsIdRouteImport } from './routes/testimonials/$id'
import { Route as TestimonialsIdMediaDownloadRouteImport } from './routes/testimonials/$id.media-download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIdRoute = TestimonialsIdRouteImport.update({
  id: '/testimonials/$id',
  path: '/testimonials/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIdMediaDownloadRoute =
  TestimonialsIdMediaDownloadRouteImport.update({
    id: '/media-download',
    path: '/media-download',
    getParentRoute: () => TestimonialsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testimonials/$id': typeof TestimonialsIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/testimonials/$id/media-download': typeof TestimonialsIdMediaDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testimonials/$id': typeof TestimonialsIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/testimonials/$id/media-download': typeof TestimonialsIdMediaDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testimonials/$id': typeof TestimonialsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/testimonials/$id/media-download': typeof TestimonialsIdMediaDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/testimonials/$id'
    | '/admin'
    | '/testimonials'
    | '/testimonials/$id/media-download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/testimonials/$id'
    | '/admin'
    | '/testimonials'
    | '/testimonials/$id/media-download'
  id:
    | '__root__'
    | '/'
    | '/testimonials/$id'
    | '/admin/'
    | '/testimonials/'
    | '/testimonials/$id/media-download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestimonialsIdRoute: typeof TestimonialsIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/$id': {
      id: '/testimonials/$id'
      path: '/testimonials/$id'
      fullPath: '/testimonials/$id'
      preLoaderRoute: typeof TestimonialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/$id/media-download': {
      id: '/testimonials/$id/media-download'
      path: '/media-download'
      fullPath: '/testimonials/$id/media-download'
      preLoaderRoute: typeof TestimonialsIdMediaDownloadRouteImport
      parentRoute: typeof TestimonialsIdRoute
    }
  }
}

interface TestimonialsIdRouteChildren {
  TestimonialsIdMediaDownloadRoute: typeof TestimonialsIdMediaDownloadRoute
}

const TestimonialsIdRouteChildren: TestimonialsIdRouteChildren = {
  TestimonialsIdMediaDownloadRoute: TestimonialsIdMediaDownloadRoute,
}

const TestimonialsIdRouteWithChildren = TestimonialsIdRoute._addFileChildren(
  TestimonialsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestimonialsIdRoute: TestimonialsIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
